- config/environments/production.rb
force a redirection from http://www.de-fil-en-aiguille.eu to https://www.de-fil-en-aiguille.eu thanks to force_ssl option ! Our website is now secure for visitors :)
> redirect our website to https://www.de-fil-en-aiguille.eu

- app/models/user.rb
- db/migrate/20200526092503_add_columns_to_offers.rb
- db/migrate/20200526092721_remove_columns_from_products.rb
- db/migrate/20200526101550_change_type_in_product.rb
- db/schema.rb
- db/seeds.rb
In db: 
- remove fields "details" and "price" in products table
- add fields "description" and "price" to offers table
- rename field "type" by "product-type" in products table
In seed:
- creation of 5 users
- creation of 3 products
- creation of 5 offers
> seed and db updates

- config/database.yml
=> so that we can query our db with Postico :)
> adding postico setup

- db/migrate/20200527173256_add_budget_to_projects.rb
- db/schema.rb
Just a petite migration to add "budget" to projects. I updated the DB schema in KITT.
> add budget as float to projects table

- app/views/shared/_navbar.html.erb
- add all available routes to navbar links
- remove active class set by error on all links
- remove "aide" since we have no support (for now)
- add an if to differenciate connected user / not connected user
> add links to navbar and correct active class

- app/controllers/offers_controller.rb
- app/controllers/projects_controller.rb
- app/views/offers/index.html.erb
- app/views/projects/new.html.erb
> fix path new project on index

- app/controllers/pages_controller.rb
- app/views/pages/dashboard.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
Initiated the dashboard routes / actions / views
> initiated dashboard routes / add the link to navbar

- app/assets/stylesheets/components/_map.scss
- app/controllers/offers_controller.rb
- app/controllers/pages_controller.rb
- app/javascript/plugins/init_mapbox.js
- app/views/offers/_info_window.html.erb
- app/views/offers/index.html.erb
- app/views/pages/home.html.erb
- db/seeds.rb
les amis je viens de faire une grosse PR avec :
correction de bug d'intégration entre homepage et index page
correction bug map + bug search 
ajout des users qui ont "0" stock et qui apparaissent en grisés dans la map 
ajout de quelques users et offres dans la seed pour justement avoir des users qui n'ont pas de stock 
ajout des params nécessaires à la page Project_new pour @Elise Dindault
> PR - Correction des bugs sur l'index / Intégration avec homepage + project_new / Amélioration de la seed / Amélioration de la map

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/components/_select.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/javascript/components/init_select2.js
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/views/offers/index.html.erb
- app/views/pages/home.html.erb
- package.json
- yarn.lock
> Javascript plugin select2

- app/controllers/projects_controller.rb
- app/views/projects/new.html.erb
- fix display of product value (default : search param)
- creation works and redirects to project show page
> create project finalized

- app/assets/stylesheets/components/_footer.scss
- app/views/projects/show.html.erb
- app/views/shared/_footer.html.erb
finalement j'ai juste fait un truc sur le footer 💤
> Front recapitulatif

- app/controllers/projects_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_calendar_display.js
- app/javascript/plugins/init_list_group_items_action.js
- app/javascript/plugins/init_mapbox.js
- app/models/project.rb
- app/views/layouts/application.html.erb
- app/views/projects/new.html.erb
Creation of matches with offers selected when a project is created.
> Matches creation

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
> we fix the bug for homepage

- app/javascript/packs/application.js
- app/javascript/plugins/flatpickr.js
- app/javascript/plugins/init_list_group_items_action.js
- app/javascript/plugins/init_mapbox.js
- app/views/projects/new.html.erb
> fix js on new project page

- app/assets/stylesheets/components/_collaborateur.scss
- app/views/projects/show.html.erb
- db/seeds.rb
Reverts Yanka13/filenaiguille#46
> Revert "Improving front projects"

- app/assets/stylesheets/components/_collaborateur.scss
- app/assets/stylesheets/components/_dashboard.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/pages_controller.rb
- app/controllers/projects_controller.rb
- app/views/layouts/application.html.erb
- app/views/offers/index.html.erb
- app/views/pages/dashboard.html.erb
- app/views/projects/new.html.erb
- app/views/projects/show.html.erb
Project show:
- Add links for project show
- Add number of mask makers 
- Add distance
Project creation : 
Add the number of mask makers to notify 
Hide the offers with 0 stock
Add the stock
> Quick win + back-end project/matches + show project

- app/assets/stylesheets/components/_navbar.scss
- app/views/layouts/application.html.erb
Mise à jour de la navbar pour qu'elle ne s'affiche pas sur la homepage
> update navbar homepage

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_product_checkboxes.scss
- app/controllers/projects_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_product_choice.js
- app/views/projects/new.html.erb
- db/schema.rb
- labels en FR
- change design
- ajout description dans la création du projet
> design new-project + french labels

- app/assets/stylesheets/pages/_index.scss
- app/javascript/components/init_select2.js
- app/views/offers/_info_window.html.erb
- app/views/offers/index.html.erb
- allongement de l'image de la bannière homepage 
- search bar : label, fond en blanc, espacement des forms
> search bar

- app/controllers/offers_controller.rb
- app/views/offers/_info_window.html.erb
- app/views/offers/_notification.html.erb
- app/views/shared/_dashboard.html.erb
Hey, 
I change the index search : 
Only OFFERS WITHOUT matches can be seen on the index pages map :) 
Also add all the stock > 0 in green in the index 
And quick win for notification
> modify the index / stock green /

- app/javascript/plugins/init_counter_offers.js
Very small modif in order to take into account the float type of price variable.
> rectify number type for price float

- app/assets/stylesheets/projects/_new.scss
- app/controllers/projects_controller.rb
- app/javascript/plugins/init_counter_offers.js
- app/views/projects/new.html.erb
- align input for quantities (but still not optimal)
- put quantity and budget on same line
> design project new

- config/cable.yml
Hey, I just change the config files as mentioned in the lecture of Action Cable to allow it on Heroku
> fix notifications issue on heroku

- app/controllers/pages_controller.rb
- app/views/pages/dashboard.html.erb
Hey, I add markers on the dashboard main's page so that we can see : 
- all current user' mask makers
- the address of the current user
> Add the markers on the dashboard map 

- app/views/offers/index.html.erb
change the price per product minimum to 0
> minimum 0 to product price

- app/assets/stylesheets/components/_product_checkboxes.scss
- app/assets/stylesheets/projects/_new.scss
- app/views/projects/new.html.erb
> design ok on projects new

- app/views/projects/index.html.erb
- app/views/projects/new.html.erb
- app/views/projects/show.html.erb
- status wording
- text white on button project new
> Final modifs

- app/controllers/offers_controller.rb
- db/seeds.rb
Change the booking system : now if you book an offer, it will still appear on the map and you can order it again (useful for the demo)
Also change the seed : offer with 0 stock no longer appears on the map
> fix the bug

- app/controllers/offers_controller.rb
authorize people to see the index without log in
> authorize people to see the index without log in
